// src/lib/curriculumData.ts
// CBSE-ONLY: Subjects for LKG-Class 8 with verified NCERT chapters.
// Flat grade → subject → chapters map.
//
// SUBJECT COVERAGE PER GRADE:
// LKG/UKG  : MATH, ENGLISH, EVS (includes General Awareness), HINDI only.
// Class 1-2: MATH, ENGLISH, EVS, HINDI only.
// Class 3-5: MATH, ENGLISH, EVS, HINDI only. EVS is the integrated Science/Social studies.
// Class 6-8: MATH, SCIENCE, ENGLISH, HINDI, SST. EVS is removed.

export type Subject = "MATH" | "SCIENCE" | "ENGLISH" | "EVS" | "HINDI" | "SST";

export interface ChapterOrTopic {
  id: string;
  name: string;
}

export const CURRICULUM_DATA: Record<string, Record<Subject, ChapterOrTopic[]>> = {
  LKG: {
    MATH: [
      { id: "lkg-math-ch1", name: "Number Work: Counting & Recognition 1 to 50" },
      { id: "lkg-math-ch2", name: "Number Writing & Missing Numbers 1 to 10" },
      { id: "lkg-math-ch3", name: "Number Names (1 to 10)" },
      { id: "lkg-math-ch4", name: "Comparing Quantities (More/Less, Big/Small, Tall/Short)" },
      { id: "lkg-math-ch5", name: "Primary & Secondary Colors" },
      { id: "lkg-math-ch6", name: "Basic Shapes (Circle, Square, Triangle, Rectangle)" }
    ],
    ENGLISH: [
      { id: "lkg-eng-ch1", name: "Pre-writing Strokes (Standing, Sleeping, Slanting Lines & Curves)" },
      { id: "lkg-eng-ch2", name: "Letter Recognition & Tracing: Capital A to Z" },
      { id: "lkg-eng-ch3", name: "Letter Recognition & Tracing: Small a to z" },
      { id: "lkg-eng-ch4", name: "Phonics: Letter Sounds" },
      { id: "lkg-eng-ch5", name: "Two-Letter & Three-Letter Words (CVC: bat, cat, etc.)" },
      { id: "lkg-eng-ch6", name: "Simple Rhyming Words" },
      { id: "lkg-eng-ch7", name: "Use of a/an" },
      { id: "lkg-eng-ch8", name: "Use of This/That" },
      { id: "lkg-eng-ch9", name: "Singular/Plural (One and Many)" }
    ],
    EVS: [
      { id: "lkg-evs-ch1", name: "Myself (Name, Age, Gender, Body Parts, Favorites)" },
      { id: "lkg-evs-ch2", name: "Community Helpers (Doctor, Teacher, Policeman, etc.)" },
      { id: "lkg-evs-ch3", name: "Modes of Transport (Road, Rail, Air)" },
      { id: "lkg-evs-ch4", name: "Animals (Domestic, Wild, Water) & Animal Sounds" },
      { id: "lkg-evs-ch5", name: "My Family & Home (Relationships & Home Safety)" },
      { id: "lkg-evs-ch6", name: "Good Habits & Table Manners" },
      { id: "lkg-evs-ch7", name: "Festivals, Seasons & Traffic Rules" }
    ],
    HINDI: [
      { id: "lkg-hin-ch1", name: "स्वर पहचान और लेखन (अ से अः)" },
      { id: "lkg-hin-ch2", name: "व्यंजन पहचान और लेखन (क से ज्ञ)" }
    ],
    SCIENCE: [],
    SST: []
  },

  UKG: {
    MATH: [
      { id: "ukg-math-ch1", name: "Numbers 1 to 200: Writing & Recognition" },
      { id: "ukg-math-ch2", name: "Before, After, and Between (1 to 100)" },
      { id: "ukg-math-ch3", name: "Backward Counting (50 to 1)" },
      { id: "ukg-math-ch4", name: "Comparing Numbers using Comparison Signs (>, <, =)" },
      { id: "ukg-math-ch5", name: "Single-Digit Picture Addition & Subtraction" },
      { id: "ukg-math-ch6", name: "Numeric Calculations without Objects (Single-Digit)" },
      { id: "ukg-math-ch7", name: "Complex Shapes (Semi-circle, Diamond, Oval)" },
      { id: "ukg-math-ch8", name: "Sorting Patterns" },
      { id: "ukg-math-ch9", name: "Skip Counting by 2s and 5s" },
      { id: "ukg-math-ch10", name: "Reading Basic Clock Time & Money Currencies" }
    ],
    ENGLISH: [
      { id: "ukg-eng-ch1", name: "Capital & Small Letters (A-Z, a-z)" },
      { id: "ukg-eng-ch2", name: "Vowels and Consonants" },
      { id: "ukg-eng-ch3", name: "Tracking Initial Blends" },
      { id: "ukg-eng-ch4", name: "Words Formed from Basic Vowels" },
      { id: "ukg-eng-ch5", name: "Singular/Plural (One and Many)" },
      { id: "ukg-eng-ch6", name: "Positioning Words (In, On, Under)" },
      { id: "ukg-eng-ch7", name: "Pairing Articles (a/an)" },
      { id: "ukg-eng-ch8", name: "Sight Word Flashcards" },
      { id: "ukg-eng-ch9", name: "Reading Short Three-Letter CVC Words (cat, pin, sun)" },
      { id: "ukg-eng-ch10", name: "Pronouncing Simple Rhyming Words" },
      { id: "ukg-eng-ch11", name: "Reading Introductory Sentences Aloud" }
    ],
    EVS: [
      { id: "ukg-evs-ch1", name: "Our Environment: Living and Non-Living Objects" },
      { id: "ukg-evs-ch2", name: "Safety & Traffic Rules (Traffic Signals, Pedestrian Rules)" },
      { id: "ukg-evs-ch3", name: "Home Safety & Avoiding Hazards" },
      { id: "ukg-evs-ch4", name: "Pollution Awareness (Air, Water, Sound)" },
      { id: "ukg-evs-ch5", name: "Self-Identity: Body Parts (Internal/External) & Five Senses" },
      { id: "ukg-evs-ch6", name: "Family Structures & Relationships" },
      { id: "ukg-evs-ch7", name: "The Living World: Animals (Domestic, Wild, Water), Young Ones & Sounds" },
      { id: "ukg-evs-ch8", name: "Identifying Plants & Flowers" },
      { id: "ukg-evs-ch9", name: "Modes of Transport (Land, Air, Water)" },
      { id: "ukg-evs-ch10", name: "Seasons (Summer, Monsoon, Winter) & National Festivals" }
    ],
    HINDI: [
      { id: "ukg-hin-ch1", name: "स्वर मात्राएँ (आ से औ)" },
      { id: "ukg-hin-ch2", name: "बिना मात्रा के शब्द (दो और तीन अक्षर के शब्द)" },
      { id: "ukg-hin-ch3", name: "अनुस्वार और चन्द्रबिन्दु" }
    ],
    SCIENCE: [],
    SST: []
  },

  "Class 1": {
    MATH: [
      { id: "c1-math-ch1", name: "Shapes and Space" },
      { id: "c1-math-ch2", name: "Numbers from One to Nine" },
      { id: "c1-math-ch3", name: "Addition" },
      { id: "c1-math-ch4", name: "Subtraction" },
      { id: "c1-math-ch5", name: "Numbers from Ten to Twenty" },
      { id: "c1-math-ch6", name: "Time" },
      { id: "c1-math-ch7", name: "Measurement" },
      { id: "c1-math-ch8", name: "Numbers from Twenty-one to Fifty" },
      { id: "c1-math-ch9", name: "Data Handling" },
      { id: "c1-math-ch10", name: "Patterns" },
      { id: "c1-math-ch11", name: "Numbers (up to 99)" },
      { id: "c1-math-ch12", name: "Money" },
      { id: "c1-math-ch13", name: "How Many" }
    ],
    ENGLISH: [
      { id: "c1-eng-ch1", name: "Unit 1: A Happy Child & Three Little Pigs" },
      { id: "c1-eng-ch2", name: "Unit 2: After a Bath & The Bubble, the Straw, and the Shoe" },
      { id: "c1-eng-ch3", name: "Unit 3: One Little Kitten & Lalu and Peelu" },
      { id: "c1-eng-ch4", name: "Unit 4: Once I Saw a Little Bird & Mittu and the Yellow Mango" },
      { id: "c1-eng-ch5", name: "Unit 5: Merry-Go-Round & Circle" },
      { id: "c1-eng-ch6", name: "Unit 6: If I Were an Apple & Our Tree" },
      { id: "c1-eng-ch7", name: "Unit 7: A Kite & Sundari" },
      { id: "c1-eng-ch8", name: "Unit 8: A Little Turtle & The Tiger and the Mosquito" },
      { id: "c1-eng-ch9", name: "Unit 9: Clouds & Anandi's Rainbow" },
      { id: "c1-eng-ch10", name: "Unit 10: Flying-Man & The Tailor and His Friend" },
      { id: "c1-eng-gr", name: "Grammar: Naming Words, Singular/Plural, Pronouns, Verbs, Adjectives" }
    ],
    EVS: [
      { id: "c1-evs-ch1", name: "About Myself & My Body Parts" },
      { id: "c1-evs-ch2", name: "The Food We Eat" },
      { id: "c1-evs-ch3", name: "Clothes We Wear" },
      { id: "c1-evs-ch4", name: "Our Shelter: Types of Houses" },
      { id: "c1-evs-ch5", name: "Plants and Animals Around Us" },
      { id: "c1-evs-ch6", name: "My Family & Friends" },
      { id: "c1-evs-ch7", name: "People Who Help Us (Community Helpers)" },
      { id: "c1-evs-ch8", name: "Safety Rules & Transport" }
    ],
    HINDI: [
      { id: "c1-hin-ch1", name: "झूला" },
      { id: "c1-hin-ch2", name: "आम की कहानी" },
      { id: "c1-hin-ch3", name: "आम की टोकरी" },
      { id: "c1-hin-ch4", name: "पत्ते ही पत्ते" },
      { id: "c1-hin-ch5", name: "पकौड़ी" },
      { id: "c1-hin-ch6", name: "छुक-छुक गाड़ी" },
      { id: "c1-hin-ch7", name: "रसोईघर" },
      { id: "c1-hin-ch8", name: "चूहो! म्याऊँ सो रही है" },
      { id: "c1-hin-ch9", name: "बंदर और गिलहरी" },
      { id: "c1-hin-ch10", name: "पगड़ी" },
      { id: "c1-hin-ch11", name: "पतंग" },
      { id: "c1-hin-ch12", name: "गेंद-बल्ला" },
      { id: "c1-hin-ch13", name: "बंदर गया खेत में भाग" },
      { id: "c1-hin-ch14", name: "एक बुढ़िया" },
      { id: "c1-hin-ch15", name: "मैं भी" },
      { id: "c1-hin-ch16", name: "लालू और पीलू" },
      { id: "c1-hin-ch17", name: "नानी वाली कथा कहानी" },
      { id: "c1-hin-ch18", name: "छोटी का कमाल" },
      { id: "c1-hin-ch19", name: "चार चने" },
      { id: "c1-hin-ch20", name: "भगदड़" },
      { id: "c1-hin-ch21", name: "हलीम चला चाँद पर" },
      { id: "c1-hin-ch22", name: "हाथी चल्लम चल्लम" },
      { id: "c1-hin-ch23", name: "सात पूँछ का चूहा" },
      { id: "c1-hin-gr", name: "व्याकरण: मात्राएँ और वर्णमाला" }
    ],
    SCIENCE: [],
    SST: []
  },

  "Class 2": {
    MATH: [
      { id: "c2-math-ch1", name: "What is Long, What is Round?" },
      { id: "c2-math-ch2", name: "Counting in Groups" },
      { id: "c2-math-ch3", name: "How Much Can You Carry?" },
      { id: "c2-math-ch4", name: "Counting in Tens" },
      { id: "c2-math-ch5", name: "Patterns" },
      { id: "c2-math-ch6", name: "Footprints" },
      { id: "c2-math-ch7", name: "Jugs and Mugs" },
      { id: "c2-math-ch8", name: "Tens and Ones" },
      { id: "c2-math-ch9", name: "My Funday" },
      { id: "c2-math-ch10", name: "Add our Points" },
      { id: "c2-math-ch11", name: "Lines and Lines" },
      { id: "c2-math-ch12", name: "Give and Take" },
      { id: "c2-math-ch13", name: "The Longest Step" },
      { id: "c2-math-ch14", name: "Birds Come, Birds Go" },
      { id: "c2-math-ch15", name: "How Many Ponytails?" }
    ],
    ENGLISH: [
      { id: "c2-eng-ch1", name: "Unit 1: First Day at School & Haldi's Adventure" },
      { id: "c2-eng-ch2", name: "Unit 2: I am Lucky! & I Want" },
      { id: "c2-eng-ch3", name: "Unit 3: A Smile & The Wind and the Sun" },
      { id: "c2-eng-ch4", name: "Unit 4: Rain & Storm in the Garden" },
      { id: "c2-eng-ch5", name: "Unit 5: Zoo Manners & Funny Bunny" },
      { id: "c2-eng-ch6", name: "Unit 6: Mr. Nobody & Curlylocks and the Three Bears" },
      { id: "c2-eng-ch7", name: "Unit 7: On My Blackboard I can Draw & Make it Shorter" },
      { id: "c2-eng-ch8", name: "Unit 8: I am the Music Man & The Mumbai Musicians" },
      { id: "c2-eng-ch9", name: "Unit 9: Granny Granny Please Comb my Hair & The Magic Porridge Pot" },
      { id: "c2-eng-ch10", name: "Unit 10: Strange Talk & The Grasshopper and the Ant" },
      { id: "c2-eng-gr", name: "Grammar: Action Verbs, Adjectives, Prepositions, Articles, Question Words" }
    ],
    EVS: [
      { id: "c2-evs-ch1", name: "My Family & Neighbors" },
      { id: "c2-evs-ch2", name: "Healthy Food & Nutrition" },
      { id: "c2-evs-ch3", name: "Clothes We Wear" },
      { id: "c2-evs-ch4", name: "Safety First & Good Habits" },
      { id: "c2-evs-ch5", name: "Cleanliness & Health" },
      { id: "c2-evs-ch6", name: "Plants Around Us" },
      { id: "c2-evs-ch7", name: "Useful Animals" },
      { id: "c2-evs-ch8", name: "Air, Water and Weather" },
      { id: "c2-evs-ch9", name: "Means of Transport & Communication" },
      { id: "c2-evs-ch10", name: "Our Festivals & National Celebrations" }
    ],
    HINDI: [
      { id: "c2-hin-ch1", name: "ऊँट चला" },
      { id: "c2-hin-ch2", name: "भालू ने खेली फुटबॉल" },
      { id: "c2-hin-ch3", name: "म्याऊँ, म्याऊँ!!" },
      { id: "c2-hin-ch4", name: "अधिक बलवान कौन?" },
      { id: "c2-hin-ch5", name: "दोस्त की मदद" },
      { id: "c2-hin-ch6", name: "बहुत हुआ" },
      { id: "c2-hin-ch7", name: "मेरी किताब" },
      { id: "c2-hin-ch8", name: "तितली और कली" },
      { id: "c2-hin-ch9", name: "बुलबुल" },
      { id: "c2-hin-ch10", name: "मीठी सारंगी" },
      { id: "c2-hin-ch11", name: "टेसू राजा बीच बाज़ार" },
      { id: "c2-hin-ch12", name: "बस के नीचे बाघ" },
      { id: "c2-hin-ch13", name: "सूरज जल्दी आना जी" },
      { id: "c2-hin-ch14", name: "नटखट चूहा" },
      { id: "c2-hin-ch15", name: "एक्की-दोक्की" },
      { id: "c2-hin-gr", name: "व्याकरण: वचन, लिंग, विलोम शब्द, वाक्य रचना" }
    ],
    SCIENCE: [],
    SST: []
  },

  "Class 3": {
    MATH: [
      { id: "c3-math-ch1", name: "Chapter 1: What’s in a Name?" },
      { id: "c3-math-ch2", name: "Chapter 2: Toy Joy" },
      { id: "c3-math-ch3", name: "Chapter 3: Double Century" },
      { id: "c3-math-ch4", name: "Chapter 4: Vacation with Nani" },
      { id: "c3-math-ch5", name: "Chapter 5: Fun with Shapes" },
      { id: "c3-math-ch6", name: "Chapter 6: House of Hundreds" },
      { id: "c3-math-ch7", name: "Chapter 7: Equal Shares" },
      { id: "c3-math-ch8", name: "Chapter 8: How Heavy?" },
      { id: "c3-math-ch9", name: "Chapter 9: Dots and Lines" },
      { id: "c3-math-ch10", name: "Chapter 10: Standard Measures" },
      { id: "c3-math-ch11", name: "Chapter 11: Data Handling" }
    ],
    ENGLISH: [
      { id: "c3-eng-ch1", name: "Unit 1: Colors of Childhood" },
      { id: "c3-eng-ch2", name: "Unit 2: Wildlife Wonders" },
      { id: "c3-eng-ch3", name: "Unit 3: Friends of Nature" },
      { id: "c3-eng-ch4", name: "Unit 4: My Country, My Pride" },
      { id: "c3-eng-gr", name: "Grammar: Common & Proper Nouns, Singular/Plural, Present Continuous (-ing), Conjunctions (and, but)" }
    ],
    EVS: [
      { id: "c3-evs-ch1", name: "Chapter 1: Poonam's Day Out" },
      { id: "c3-evs-ch2", name: "Chapter 2: The Plant Fairy" },
      { id: "c3-evs-ch3", name: "Chapter 3: Water O’ Water!" },
      { id: "c3-evs-ch4", name: "Chapter 4: Our First School" },
      { id: "c3-evs-ch5", name: "Chapter 5: Chhotu's House" },
      { id: "c3-evs-ch6", name: "Chapter 6: Foods We Eat" },
      { id: "c3-evs-ch7", name: "Chapter 7: Saying without Speaking" },
      { id: "c3-evs-ch8", name: "Chapter 8: Flying High" },
      { id: "c3-evs-ch9", name: "Chapter 9: It's Raining" },
      { id: "c3-evs-ch10", name: "Chapter 10: What is Cooking" },
      { id: "c3-evs-ch11", name: "Chapter 11: From Here to There" },
      { id: "c3-evs-ch12", name: "Chapter 12: Work We Do" },
      { id: "c3-evs-ch13", name: "Chapter 13: Sharing Our Feelings" },
      { id: "c3-evs-ch14", name: "Chapter 14: The Story of Food" },
      { id: "c3-evs-ch15", name: "Chapter 15: Making Pots" },
      { id: "c3-evs-ch16", name: "Chapter 16: Games We Play" },
      { id: "c3-evs-ch17", name: "Chapter 17: Here Comes a Letter" },
      { id: "c3-evs-ch18", name: "Chapter 18: A House Like This" },
      { id: "c3-evs-ch19", name: "Chapter 19: Our Friends – Animals" },
      { id: "c3-evs-ch20", name: "Chapter 20: Drop by Drop" },
      { id: "c3-evs-ch21", name: "Chapter 21: Families Can Be Different" },
      { id: "c3-evs-ch22", name: "Chapter 22: Left-Right" },
      { id: "c3-evs-ch23", name: "Chapter 23: A Beautiful Cloth" },
      { id: "c3-evs-ch24", name: "Chapter 24: Web of Life" }
    ],
    HINDI: [
      { id: "c3-hin-ch1", name: "इकाई 1: मेरा परिवार और मैं" },
      { id: "c3-hin-ch2", name: "इकाई 2: अनमोल सीख" },
      { id: "c3-hin-ch3", name: "इकाई 3: प्रकृति और हम" },
      { id: "c3-hin-ch4", name: "इकाई 4: रंग-बिरंगे त्योहार" },
      { id: "c3-hin-gr", name: "व्याकरण: संज्ञा, विलोम शब्द, पर्यायवाची, लिंग बदलना, अपठित गद्यांश" }
    ],
    SCIENCE: [],
    SST: []
  },

  "Class 4": {
    MATH: [
      { id: "c4-math-ch1", name: "Chapter 1: Building with Bricks" },
      { id: "c4-math-ch2", name: "Chapter 2: Long and Short" },
      { id: "c4-math-ch3", name: "Chapter 3: A Trip to Bhopal" },
      { id: "c4-math-ch4", name: "Chapter 4: Tick-Tick-Tick" },
      { id: "c4-math-ch5", name: "Chapter 5: The Way the World Looks" },
      { id: "c4-math-ch6", name: "Chapter 6: The Junk Seller" },
      { id: "c4-math-ch7", name: "Chapter 7: Jugs and Mugs" },
      { id: "c4-math-ch8", name: "Chapter 8: Carts and Wheels" },
      { id: "c4-math-ch9", name: "Chapter 9: Halves and Quarters" },
      { id: "c4-math-ch10", name: "Chapter 10: Play with Patterns" },
      { id: "c4-math-ch11", name: "Chapter 11: Tables and Shares" },
      { id: "c4-math-ch12", name: "Chapter 12: How Heavy? How Light?" },
      { id: "c4-math-ch13", name: "Chapter 13: Fields and Fences" },
      { id: "c4-math-ch14", name: "Chapter 14: Smart Charts" }
    ],
    ENGLISH: [
      { id: "c4-eng-ch1", name: "Unit 1: Wake Up! & Neha's Alarm Clock" },
      { id: "c4-eng-ch2", name: "Unit 2: Noses & The Little Fir Tree" },
      { id: "c4-eng-ch3", name: "Unit 3: Run! & Nasruddin's Aim" },
      { id: "c4-eng-ch4", name: "Unit 4: Why? & Alice in Wonderland" },
      { id: "c4-eng-ch5", name: "Unit 5: Don't be Afraid of the Dark & Helen Keller" },
      { id: "c4-eng-ch6", name: "Unit 6: The Donkey / I Had a Little Pony & The Milkman's Cow" },
      { id: "c4-eng-ch7", name: "Unit 7: The Hiawatha & The Scholar's Mother Tongue" },
      { id: "c4-eng-ch8", name: "Unit 8: A Watering Rhyme & The Giving Tree" },
      { id: "c4-eng-ch9", name: "Unit 9: Books & Going to Buy a Book" },
      { id: "c4-eng-ch10", name: "Unit 10: The Naughty Boy & Pinocchio" },
      { id: "c4-eng-gr", name: "Grammar: Abstract Nouns, Pronouns, Countable/Uncountable, Adverbs of Manner, Past Continuous" }
    ],
    EVS: [
      { id: "c4-evs-ch1", name: "Chapter 1: Going to School" },
      { id: "c4-evs-ch2", name: "Chapter 2: Ear to Ear" },
      { id: "c4-evs-ch3", name: "Chapter 3: A Day with Nandu" },
      { id: "c4-evs-ch4", name: "Chapter 4: The Story of Amrita" },
      { id: "c4-evs-ch5", name: "Chapter 5: Anita and the Honeybees" },
      { id: "c4-evs-ch6", name: "Chapter 6: Omana's Journey" },
      { id: "c4-evs-ch7", name: "Chapter 7: From the Window" },
      { id: "c4-evs-ch8", name: "Chapter 8: Reaching Grandmother's House" },
      { id: "c4-evs-ch9", name: "Chapter 9: Changing Families" },
      { id: "c4-evs-ch10", name: "Chapter 10: Hu Tu Tu, Hu Tu Tu" },
      { id: "c4-evs-ch11", name: "Chapter 11: The Valley of Flowers" },
      { id: "c4-evs-ch12", name: "Chapter 12: Changing Times" },
      { id: "c4-evs-ch13", name: "Chapter 13: A River's Tale" },
      { id: "c4-evs-ch14", name: "Chapter 14: Basva's Farm" },
      { id: "c4-evs-ch15", name: "Chapter 15: From Market to Home" },
      { id: "c4-evs-ch16", name: "Chapter 16: A Busy Month" },
      { id: "c4-evs-ch17", name: "Chapter 17: Nandita in Mumbai" },
      { id: "c4-evs-ch18", name: "Chapter 18: Too Much Water, Too Little Water" },
      { id: "c4-evs-ch19", name: "Chapter 19: Abdul in the Garden" },
      { id: "c4-evs-ch20", name: "Chapter 20: Eating Together" },
      { id: "c4-evs-ch21", name: "Chapter 21: Food and Fun" },
      { id: "c4-evs-ch22", name: "Chapter 22: Duniya Mere Ghar Mein" },
      { id: "c4-evs-ch23", name: "Chapter 23: Pochampally" },
      { id: "c4-evs-ch24", name: "Chapter 24: Home and Abroad" },
      { id: "c4-evs-ch25", name: "Chapter 25: Spicy Riddles" },
      { id: "c4-evs-ch26", name: "Chapter 26: Defense Officer: Wahida" },
      { id: "c4-evs-ch27", name: "Chapter 27: Chuskit Goes to School" }
    ],
    HINDI: [
      { id: "c4-hin-ch1", name: "पाठ 1: मन के भोले-भाले बादल" },
      { id: "c4-hin-ch2", name: "पाठ 2: जैसा सवाल वैसा जवाब" },
      { id: "c4-hin-ch3", name: "पाठ 3: किरमिच की गेंद" },
      { id: "c4-hin-ch4", name: "पाठ 4: पापा जब बच्चे थे" },
      { id: "c4-hin-ch5", name: "पाठ 5: दोस्त की पोशाक" },
      { id: "c4-hin-ch6", name: "पाठ 6: नाव बनाओ नाव बनाओ" },
      { id: "c4-hin-ch7", name: "पाठ 7: दान का हिसाब" },
      { id: "c4-hin-ch8", name: "पाठ 8: कौन?" },
      { id: "c4-hin-ch9", name: "पाठ 9: स्वतंत्रता की ओर" },
      { id: "c4-hin-ch10", name: "पाठ 10: थप्प रोटी थप्प दाल" },
      { id: "c4-hin-ch11", name: "पाठ 11: पढ़क्कू की सूझ" },
      { id: "c4-hin-ch12", name: "पाठ 12: सुनीता की पहिया कुर्सी" },
      { id: "c4-hin-ch13", name: "पाठ 13: हुदहुद" },
      { id: "c4-hin-ch14", name: "पाठ 14: मुफ्त ही मुफ्त" },
      { id: "c4-hin-gr", name: "व्याकरण: क्रिया-विशेषण, मुहावरे, विराम चिह्न, कारक चिह्न, शुद्ध वर्तनी" }
    ],
    SCIENCE: [],
    SST: []
  },

  "Class 5": {
    MATH: [
      { id: "c5-math-ch1", name: "Chapter 1: The Fish Tale" },
      { id: "c5-math-ch2", name: "Chapter 2: Angles and Shapes" },
      { id: "c5-math-ch3", name: "Chapter 3: How Many Squares?" },
      { id: "c5-math-ch4", name: "Chapter 4: Parts and Wholes" },
      { id: "c5-math-ch5", name: "Chapter 5: Does it Look the Same?" },
      { id: "c5-math-ch6", name: "Chapter 6: Be My Multiple, I'll be Your Factor" },
      { id: "c5-math-ch7", name: "Chapter 7: Can You See the Pattern?" },
      { id: "c5-math-ch8", name: "Chapter 8: Mapping Your Way" },
      { id: "c5-math-ch9", name: "Chapter 9: Boxes and Sketches" },
      { id: "c5-math-ch10", name: "Chapter 10: Tenths and Hundredths" },
      { id: "c5-math-ch11", name: "Chapter 11: Area and its Boundary" },
      { id: "c5-math-ch12", name: "Chapter 12: Smart Charts" },
      { id: "c5-math-ch13", name: "Chapter 13: Ways to Multiply and Divide" },
      { id: "c5-math-ch14", name: "Chapter 14: How Big? How Heavy?" }
    ],
    ENGLISH: [
      { id: "c5-eng-ch1", name: "Unit 1: Ice-cream Man & Wonderful Waste!" },
      { id: "c5-eng-ch2", name: "Unit 2: Teamwork & Flying Together" },
      { id: "c5-eng-ch3", name: "Unit 3: Shadow & Robinson Crusoe Discovers a Footprint" },
      { id: "c5-eng-ch4", name: "Unit 4: Crying & My Elder Brother" },
      { id: "c5-eng-ch5", name: "Unit 5: The Lazy Frog & Rip Van Winkle" },
      { id: "c5-eng-ch6", name: "Unit 6: Class Discussion & The Talkative Barber" },
      { id: "c5-eng-ch7", name: "Unit 7: Topsy-Turvy Land & Gulliver’s Travels" },
      { id: "c5-eng-ch8", name: "Unit 8: Nobody’s Friend & The Little Bully" },
      { id: "c5-eng-ch9", name: "Unit 9: Sing a Song of People & Around the World" },
      { id: "c5-eng-ch10", name: "Unit 10: Malu Bhalu & Who Will be Ningthou?" },
      { id: "c5-eng-gr", name: "Grammar: Sentence Types, Conjunctions (neither...nor/either...or), Active/Passive Voice, Prepositions" }
    ],
    EVS: [
      { id: "c5-evs-ch1", name: "Chapter 1: Super Senses" },
      { id: "c5-evs-ch2", name: "Chapter 2: A Snake Charmer’s Story" },
      { id: "c5-evs-ch3", name: "Chapter 3: From Tasting to Digesting" },
      { id: "c5-evs-ch4", name: "Chapter 4: Mangoes Round the Year" },
      { id: "c5-evs-ch5", name: "Chapter 5: Seeds and Seeds" },
      { id: "c5-evs-ch6", name: "Chapter 6: Every Drop Counts" },
      { id: "c5-evs-ch7", name: "Chapter 7: Experiments with Water" },
      { id: "c5-evs-ch8", name: "Chapter 8: A Treat for Mosquitoes" },
      { id: "c5-evs-ch9", name: "Chapter 9: Up You Go!" },
      { id: "c5-evs-ch10", name: "Chapter 10: Walls Tell Stories" },
      { id: "c5-evs-ch11", name: "Chapter 11: Sunita in Space" },
      { id: "c5-evs-ch12", name: "Chapter 12: What if it Finishes...?" },
      { id: "c5-evs-ch13", name: "Chapter 13: A Shelter so High!" },
      { id: "c5-evs-ch14", name: "Chapter 14: When the Earth Shook!" },
      { id: "c5-evs-ch15", name: "Chapter 15: Blow Hot, Blow Cold" },
      { id: "c5-evs-ch16", name: "Chapter 16: Who will do this Work?" },
      { id: "c5-evs-ch17", name: "Chapter 17: Across the Wall" },
      { id: "c5-evs-ch18", name: "Chapter 18: No Place for Us?" },
      { id: "c5-evs-ch19", name: "Chapter 19: A Seed Tells a Farmer’s Story" },
      { id: "c5-evs-ch20", name: "Chapter 20: Whose Forests?" },
      { id: "c5-evs-ch21", name: "Chapter 21: Like Father, Like Daughter" },
      { id: "c5-evs-ch22", name: "Chapter 22: On the Move Again" }
    ],
    HINDI: [
      { id: "c5-hin-ch1", name: "पाठ 1: राख की रस्सी" },
      { id: "c5-hin-ch2", name: "पाठ 2: फसलों के त्योहार" },
      { id: "c5-hin-ch3", name: "पाठ 3: खिलौनेवाला" },
      { id: "c5-hin-ch4", name: "पाठ 4: नन्हा फनकार" },
      { id: "c5-hin-ch5", name: "पाठ 5: जहाँ चाह वहाँ राह" },
      { id: "c5-hin-ch6", name: "पाठ 6: चिट्ठी का सफर" },
      { id: "c5-hin-ch7", name: "पाठ 7: डाकिए की कहानी, कुँवर सिंह की जुबानी" },
      { id: "c5-hin-ch8", name: "पाठ 8: वे दिन भी क्या दिन थे" },
      { id: "c5-hin-ch9", name: "पाठ 9: एक माँ की बेबसी" },
      { id: "c5-hin-ch10", name: "पाठ 10: एक दिन की बादशाहत" },
      { id: "c5-hin-ch11", name: "पाठ 11: चावल की रोटियाँ" },
      { id: "c5-hin-ch12", name: "पाठ 12: गुरु और चेला" },
      { id: "c5-hin-ch13", name: "पाठ 13: स्वामी की दादी" },
      { id: "c5-hin-ch14", name: "पाठ 14: बाघ आया उस रात" },
      { id: "c5-hin-ch15", name: "पाठ 15: बिशन की दिलेरी" },
      { id: "c5-hin-ch16", name: "पाठ 16: पानी रे पानी" },
      { id: "c5-hin-ch17", name: "पाठ 17: छोटी सी हमारी नदी" },
      { id: "c5-hin-ch18", name: "पाठ 18: चुनौती हिमालय की" },
      { id: "c5-hin-gr", name: "व्याकरण: अनेकार्थी शब्द, वाक्यांश के लिए एक शब्द, काल भेद, उपसर्ग और प्रत्यय, पत्र/निबंध" }
    ],
    SCIENCE: [],
    SST: []
  },

  "Class 6": {
    MATH: [
      { id: "c6-math-ch1", name: "Chapter 1: Knowing Our Numbers" },
      { id: "c6-math-ch2", name: "Chapter 2: Whole Numbers" },
      { id: "c6-math-ch3", name: "Chapter 3: Playing with Numbers" },
      { id: "c6-math-ch4", name: "Chapter 4: Basic Geometrical Ideas" },
      { id: "c6-math-ch5", name: "Chapter 5: Understanding Elementary Shapes" },
      { id: "c6-math-ch6", name: "Chapter 6: Integers" },
      { id: "c6-math-ch7", name: "Chapter 7: Fractions" },
      { id: "c6-math-ch8", name: "Chapter 8: Decimals" },
      { id: "c6-math-ch9", name: "Chapter 9: Data Handling" },
      { id: "c6-math-ch10", name: "Chapter 10: Mensuration" },
      { id: "c6-math-ch11", name: "Chapter 11: Algebra" },
      { id: "c6-math-ch12", name: "Chapter 12: Ratio and Proportion" }
    ],
    SCIENCE: [
      { id: "c6-sci-ch1", name: "Chapter 1: Components of Food" },
      { id: "c6-sci-ch2", name: "Chapter 2: Sorting Materials into Groups" },
      { id: "c6-sci-ch3", name: "Chapter 3: Separation of Substances" },
      { id: "c6-sci-ch4", name: "Chapter 4: Getting to Know Plants" },
      { id: "c6-sci-ch5", name: "Chapter 5: Body Movements" },
      { id: "c6-sci-ch6", name: "Chapter 6: The Living Organisms" },
      { id: "c6-sci-ch7", name: "Chapter 7: Motion and Measurement of Distances" },
      { id: "c6-sci-ch8", name: "Chapter 8: Light, Shadows and Reflections" },
      { id: "c6-sci-ch9", name: "Chapter 9: Electricity and Circuits" },
      { id: "c6-sci-ch10", name: "Chapter 10: Fun with Magnets" },
      { id: "c6-sci-ch11", name: "Chapter 11: Air Around Us" }
    ],
    ENGLISH: [
      { id: "c6-eng-ch1", name: "Prose: Who Did Patrick's Homework?" },
      { id: "c6-eng-ch2", name: "Prose: How the Dog Found Himself a New Master" },
      { id: "c6-eng-ch3", name: "Prose: Taro's Reward" },
      { id: "c6-eng-ch4", name: "Prose: An Indian-American Woman in Space (Kalpana Chawla)" },
      { id: "c6-eng-ch5", name: "Prose: A Different Kind of School" },
      { id: "c6-eng-ch6", name: "Prose: Fair Play" },
      { id: "c6-eng-ch7", name: "Prose: The Banyan Tree" },
      { id: "c6-eng-ch8", name: "Poetry: A House A Home" },
      { id: "c6-eng-ch9", name: "Poetry: The Kite" },
      { id: "c6-eng-ch10", name: "Poetry: The Quarrel" },
      { id: "c6-eng-gr", name: "Grammar: Abstract/Collective Nouns, Relative Pronouns, Continuous Tenses, Modals" }
    ],
    HINDI: [
      { id: "c6-hin-ch1", name: "वह चिड़िया जो (कविता)" },
      { id: "c6-hin-ch2", name: "बचपन" },
      { id: "c6-hin-ch3", name: "नादान दोस्त" },
      { id: "c6-hin-ch4", name: "चाँद से थोड़ी सी गप्पें (कविता)" },
      { id: "c6-hin-ch5", name: "साथी हाथ बढ़ाना (गीत)" },
      { id: "c6-hin-ch6", name: "ऐसे–ऐसे (एकांकी)" },
      { id: "c6-hin-ch7", name: "टिकट अलबम" },
      { id: "c6-hin-ch8", name: "झाँसी की रानी (कविता)" },
      { id: "c6-hin-ch9", name: "जो देखकर भी नहीं देखते" },
      { id: "c6-hin-ch10", name: "संसार पुस्तक है" },
      { id: "c6-hin-ch11", name: "मैं सबसे छोटी होऊं (कविता)" },
      { id: "c6-hin-ch12", name: "लोकगीत" },
      { id: "c6-hin-ch13", name: "नौकर" },
      { id: "c6-hin-ch14", name: "वन के मार्ग में (सवैया)" },
      { id: "c6-hin-gr", name: "व्याकरण: वर्ण विचार, संज्ञा, सर्वनाम, विशेषण, क्रिया" }
    ],
    SST: [
      { id: "c6-hist-ch1", name: "History Ch 1: What, Where, How and When?" },
      { id: "c6-hist-ch2", name: "History Ch 2: From Hunting-Gathering to Growing Food" },
      { id: "c6-hist-ch3", name: "History Ch 3: In the Earliest Cities" },
      { id: "c6-hist-ch4", name: "History Ch 4: What Books and Burials Tell Us" },
      { id: "c6-hist-ch5", name: "History Ch 5: Kingdoms, Kings and an Early Republic" },
      { id: "c6-hist-ch6", name: "History Ch 6: New Questions and Ideas" },
      { id: "c6-hist-ch7", name: "History Ch 7: From a Kingdom to an Empire" },
      { id: "c6-hist-ch8", name: "History Ch 8: Villages, Towns and Trade" },
      { id: "c6-hist-ch9", name: "History Ch 9: New Empires and Kingdoms" },
      { id: "c6-hist-ch10", name: "History Ch 10: Buildings, Paintings and Books" },
      { id: "c6-geo-ch1", name: "Geography Ch 1: The Earth in the Solar System" },
      { id: "c6-geo-ch2", name: "Geography Ch 2: Globe: Latitudes and Longitudes" },
      { id: "c6-geo-ch3", name: "Geography Ch 3: Motions of the Earth" },
      { id: "c6-geo-ch4", name: "Geography Ch 4: Maps" },
      { id: "c6-geo-ch5", name: "Geography Ch 5: Major Domains of the Earth" },
      { id: "c6-geo-ch6", name: "Geography Ch 6: Our Country – India" },
      { id: "c6-civ-ch1", name: "Civics Ch 1: Understanding Diversity" },
      { id: "c6-civ-ch2", name: "Civics Ch 2: Diversity and Discrimination" },
      { id: "c6-civ-ch3", name: "Civics Ch 3: What is Government?" },
      { id: "c6-civ-ch4", name: "Civics Ch 4: Panchayati Raj" },
      { id: "c6-civ-ch5", name: "Civics Ch 5: Rural Administration" },
      { id: "c6-civ-ch6", name: "Civics Ch 6: Urban Administration" },
      { id: "c6-civ-ch7", name: "Civics Ch 7: Rural Livelihoods" },
      { id: "c6-civ-ch8", name: "Civics Ch 8: Urban Livelihoods" }
    ],
    EVS: []
  },

  "Class 7": {
    MATH: [
      { id: "c7-math-ch1", name: "Chapter 1: Integers" },
      { id: "c7-math-ch2", name: "Chapter 2: Fractions and Decimals" },
      { id: "c7-math-ch3", name: "Chapter 3: Data Handling" },
      { id: "c7-math-ch4", name: "Chapter 4: Simple Equations" },
      { id: "c7-math-ch5", name: "Chapter 5: Lines and Angles" },
      { id: "c7-math-ch6", name: "Chapter 6: The Triangle and its Properties" },
      { id: "c7-math-ch7", name: "Chapter 7: Comparing Quantities" },
      { id: "c7-math-ch8", name: "Chapter 8: Rational Numbers" },
      { id: "c7-math-ch9", name: "Chapter 9: Perimeter and Area" },
      { id: "c7-math-ch10", name: "Chapter 10: Algebraic Expressions" },
      { id: "c7-math-ch11", name: "Chapter 11: Exponents and Powers" },
      { id: "c7-math-ch12", name: "Chapter 12: Symmetry" },
      { id: "c7-math-ch13", name: "Chapter 13: Visualising Solid Shapes" }
    ],
    SCIENCE: [
      { id: "c7-sci-ch1", name: "Chapter 1: Nutrition in Plants" },
      { id: "c7-sci-ch2", name: "Chapter 2: Nutrition in Animals" },
      { id: "c7-sci-ch3", name: "Chapter 3: Heat" },
      { id: "c7-sci-ch4", name: "Chapter 4: Acids, Bases and Salts" },
      { id: "c7-sci-ch5", name: "Chapter 5: Physical and Chemical Changes" },
      { id: "c7-sci-ch6", name: "Chapter 6: Respiration in Organisms" },
      { id: "c7-sci-ch7", name: "Chapter 7: Transportation in Animals and Plants" },
      { id: "c7-sci-ch8", name: "Chapter 8: Reproduction in Plants" },
      { id: "c7-sci-ch9", name: "Chapter 9: Motion and Time" },
      { id: "c7-sci-ch10", name: "Chapter 10: Electric Current and its Effects" },
      { id: "c7-sci-ch11", name: "Chapter 11: Light" },
      { id: "c7-sci-ch12", name: "Chapter 12: Forests: Our Lifeline" },
      { id: "c7-sci-ch13", name: "Chapter 13: Wastewater Story" }
    ],
    ENGLISH: [
      { id: "c7-eng-ch1", name: "Chapter 1: Three Questions" },
      { id: "c7-eng-ch2", name: "Chapter 2: A Gift of Chappals" },
      { id: "c7-eng-ch3", name: "Chapter 3: Gopal and the Hilsa Fish" },
      { id: "c7-eng-ch4", name: "Chapter 4: The Ashes That Made Trees Bloom" },
      { id: "c7-eng-ch5", name: "Chapter 5: Quality" },
      { id: "c7-eng-ch6", name: "Chapter 6: Expert Detectives" },
      { id: "c7-eng-ch7", name: "Chapter 7: The Invention of Vita-Wonk" },
      { id: "c7-eng-ch8", name: "Chapter 8: Fire: Friend and Foe" },
      { id: "c7-eng-gr", name: "Grammar: Direct & Indirect Speech, Transitive/Intransitive Verbs, If Conditionals, Gerunds & Infinitives" }
    ],
    HINDI: [
      { id: "c7-hin-ch1", name: "हम पंछी उन्मुक्त गगन के (कविता)" },
      { id: "c7-hin-ch2", name: "हिमालय की बेटियाँ" },
      { id: "c7-hin-ch3", name: "कठपुतली (कविता)" },
      { id: "c7-hin-ch4", name: "मिठाईवाला" },
      { id: "c7-hin-ch5", name: "पापा खो गए (नाटक)" },
      { id: "c7-hin-ch6", name: "शाम — एक किसान (कविता)" },
      { id: "c7-hin-ch7", name: "अपूर्व अनुभव" },
      { id: "c7-hin-ch8", name: "रहीम के दोहे (कविता)" },
      { id: "c7-hin-ch9", name: "चिड़िया की बच्ची" },
      { id: "c7-hin-ch10", name: "कंचा" },
      { id: "c7-hin-ch11", name: "एक तिनका (कविता)" },
      { id: "c7-hin-ch12", name: "खानपान की बदलती तस्वीर" },
      { id: "c7-hin-ch13", name: "नीलकंठ" },
      { id: "c7-hin-ch14", name: "भोर और बरखा (कविता)" },
      { id: "c7-hin-ch15", name: "वीर कुंवर सिंह" },
      { id: "c7-hin-gr", name: "व्याकरण: उपसर्ग, प्रत्यय, वाक्य-रचना, काल" }
    ],
    SST: [
      { id: "c7-hist-ch1", name: "History Ch 1: Tracing Changes Through a Thousand Years" },
      { id: "c7-hist-ch2", name: "History Ch 2: New Kings and Kingdoms" },
      { id: "c7-hist-ch3", name: "History Ch 3: Delhi: 12th to 15th Century" },
      { id: "c7-hist-ch4", name: "History Ch 4: The Mughals: 16th to 17th Century" },
      { id: "c7-hist-ch5", name: "History Ch 5: Tribes, Nomads and Settled Communities" },
      { id: "c7-hist-ch6", name: "History Ch 6: Devotional Paths to the Divine" },
      { id: "c7-hist-ch7", name: "History Ch 7: The Making of Regional Cultures" },
      { id: "c7-hist-ch8", name: "History Ch 8: Eighteenth-Century Political Formations" },
      { id: "c7-geo-ch1", name: "Geography Ch 1: Environment" },
      { id: "c7-geo-ch2", name: "Geography Ch 2: Inside Our Earth" },
      { id: "c7-geo-ch3", name: "Geography Ch 3: Our Changing Earth" },
      { id: "c7-geo-ch4", name: "Geography Ch 4: Air" },
      { id: "c7-geo-ch5", name: "Geography Ch 5: Water" },
      { id: "c7-geo-ch6", name: "Geography Ch 6: Human–Environment Interactions" },
      { id: "c7-geo-ch7", name: "Geography Ch 7: Life in the Deserts" },
      { id: "c7-civ-ch1", name: "Civics Ch 1: On Equality" },
      { id: "c7-civ-ch2", name: "Civics Ch 2: Role of the Government in Health" },
      { id: "c7-civ-ch3", name: "Civics Ch 3: How the State Government Works" },
      { id: "c7-civ-ch4", name: "Civics Ch 4: Growing Up as Boys and Girls" },
      { id: "c7-civ-ch5", name: "Civics Ch 5: Women Change the World" },
      { id: "c7-civ-ch6", name: "Civics Ch 6: Understanding Media" },
      { id: "c7-civ-ch7", name: "Civics Ch 7: Markets Around Us" },
      { id: "c7-civ-ch8", name: "Civics Ch 8: A Shirt in the Market" }
    ],
    EVS: []
  },

  "Class 8": {
    MATH: [
      { id: "c8-math-ch1", name: "Chapter 1: Rational Numbers" },
      { id: "c8-math-ch2", name: "Chapter 2: Linear Equations in One Variable" },
      { id: "c8-math-ch3", name: "Chapter 3: Understanding Quadrilaterals" },
      { id: "c8-math-ch4", name: "Chapter 4: Data Handling" },
      { id: "c8-math-ch5", name: "Chapter 5: Squares and Square Roots" },
      { id: "c8-math-ch6", name: "Chapter 6: Cubes and Cube Roots" },
      { id: "c8-math-ch7", name: "Chapter 7: Comparing Quantities" },
      { id: "c8-math-ch8", name: "Chapter 8: Algebraic Expressions and Identities" },
      { id: "c8-math-ch9", name: "Chapter 9: Mensuration" },
      { id: "c8-math-ch10", name: "Chapter 10: Exponents and Powers" },
      { id: "c8-math-ch11", name: "Chapter 11: Direct and Inverse Proportions" },
      { id: "c8-math-ch12", name: "Chapter 12: Factorisation" },
      { id: "c8-math-ch13", name: "Chapter 13: Introduction to Graphs" }
    ],
    SCIENCE: [
      { id: "c8-sci-ch1", name: "Chapter 1: Crop Production and Management" },
      { id: "c8-sci-ch2", name: "Chapter 2: Microorganisms: Friend and Foe" },
      { id: "c8-sci-ch3", name: "Chapter 3: Coal and Petroleum" },
      { id: "c8-sci-ch4", name: "Chapter 4: Combustion and Flame" },
      { id: "c8-sci-ch5", name: "Chapter 5: Conservation of Plants and Animals" },
      { id: "c8-sci-ch6", name: "Chapter 6: Reproduction in Animals" },
      { id: "c8-sci-ch7", name: "Chapter 7: Reaching the Age of Adolescence" },
      { id: "c8-sci-ch8", name: "Chapter 8: Force and Pressure" },
      { id: "c8-sci-ch9", name: "Chapter 9: Friction" },
      { id: "c8-sci-ch10", name: "Chapter 10: Sound" },
      { id: "c8-sci-ch11", name: "Chapter 11: Chemical Effects of Electric Current" },
      { id: "c8-sci-ch12", name: "Chapter 12: Some Natural Phenomena" },
      { id: "c8-sci-ch13", name: "Chapter 13: Light" }
    ],
    ENGLISH: [
      { id: "c8-eng-ch1", name: "Chapter 1: The Best Christmas Present in the World" },
      { id: "c8-eng-ch2", name: "Chapter 2: The Tsunami" },
      { id: "c8-eng-ch3", name: "Chapter 3: Glimpses of the Past" },
      { id: "c8-eng-ch4", name: "Chapter 4: Bepin Choudhury's Lapse of Memory" },
      { id: "c8-eng-ch5", name: "Chapter 5: The Summit Within" },
      { id: "c8-eng-ch6", name: "Chapter 6: This is Jody's Fawn" },
      { id: "c8-eng-ch7", name: "Chapter 7: A Visit to Cambridge" },
      { id: "c8-eng-ch8", name: "Chapter 8: A Short Monsoon Diary" },
      { id: "c8-eng-gr", name: "Grammar: Active/Passive (Advanced), Subject-Verb Agreement, Conditionals, Relative Clauses" }
    ],
    HINDI: [
      { id: "c8-hin-ch1", name: "लाख की चूड़ियाँ" },
      { id: "c8-hin-ch2", name: "बस की यात्रा" },
      { id: "c8-hin-ch3", name: "दीवानों की हस्ती (कविता)" },
      { id: "c8-hin-ch4", name: "भगवान के डाकिए (कविता)" },
      { id: "c8-hin-ch5", name: "क्या निराश हुआ जाए" },
      { id: "c8-hin-ch6", name: "यह सबसे कठिन समय नहीं (कविता)" },
      { id: "c8-hin-ch7", name: "कबीर की साखियाँ (कविता)" },
      { id: "c8-hin-ch8", name: "सुदामा चरित (कविता)" },
      { id: "c8-hin-ch9", name: "जहाँ पहिया है" },
      { id: "c8-hin-ch10", name: "अकबरी लोटा" },
      { id: "c8-hin-ch11", name: "सूरदास के पद (कविता)" },
      { id: "c8-hin-ch12", name: "पानी की कहानी" },
      { id: "c8-hin-ch13", name: "बाज और साँप" },
      { id: "c8-hin-gr", name: "व्याकरण: अलंकार, रस, वाक्य-संशोधन, संधि" }
    ],
    SST: [
      { id: "c8-hist-ch1", name: "History Ch 1: How, When and Where" },
      { id: "c8-hist-ch2", name: "History Ch 2: From Trade to Territory" },
      { id: "c8-hist-ch3", name: "History Ch 3: Ruling the Countryside" },
      { id: "c8-hist-ch4", name: "History Ch 4: Tribals, Dikus and the Vision of a Golden Age" },
      { id: "c8-hist-ch5", name: "History Ch 5: When People Rebel: 1857 and After" },
      { id: "c8-hist-ch6", name: "History Ch 6: Civilising the “Native”, Educating the Nation" },
      { id: "c8-hist-ch7", name: "History Ch 7: Women, Caste and Reform" },
      { id: "c8-hist-ch8", name: "History Ch 8: The Making of the National Movement" },
      { id: "c8-geo-ch1", name: "Geography Ch 1: Resources" },
      { id: "c8-geo-ch2", name: "Geography Ch 2: Land, Soil, Water, Natural Vegetation and Wildlife Resources" },
      { id: "c8-geo-ch3", name: "Geography Ch 3: Agriculture" },
      { id: "c8-geo-ch4", name: "Geography Ch 4: Industries" },
      { id: "c8-geo-ch5", name: "Geography Ch 5: Human Resources" },
      { id: "c8-civ-ch1", name: "Civics Ch 1: The Indian Constitution" },
      { id: "c8-civ-ch2", name: "Civics Ch 2: Understanding Secularism" },
      { id: "c8-civ-ch3", name: "Civics Ch 3: Parliament and the Making of Laws" },
      { id: "c8-civ-ch4", name: "Civics Ch 4: Judiciary" },
      { id: "c8-civ-ch5", name: "Civics Ch 5: Understanding Marginalisation" },
      { id: "c8-civ-ch6", name: "Civics Ch 6: Confronting Marginalisation" },
      { id: "c8-civ-ch7", name: "Civics Ch 7: Public Facilities" },
      { id: "c8-civ-ch8", name: "Civics Ch 8: Law and Social Justice" }
    ],
    EVS: []
  }
};
